Import the modules 

In [1]:
import numpy as np

My Data

In [121]:
data=[[ 23,  3,  8,6562],

         [  15,  2,  7,4569],

         [ 24,  4,  9,6897],

         [  29,  5,  4,7562],

         [ 31,  7,  6,8234]

         ]

Get the X and Y**values**

In [122]:
x=[]
y=[]
for i in range(len(data)):
  x.append(data[i][0:-1])
  y.append(data[i][-1])
print(x)
print(y)

[[23, 3, 8], [15, 2, 7], [24, 4, 9], [29, 5, 4], [31, 7, 6]]
[6562, 4569, 6897, 7562, 8234]


Convert X and Y to numpy arrays

In [123]:
x=np.array(x)
ones=np.ones((x.shape[0],1))
x=np.concatenate((ones,x),axis=1)
print(x)
print(x.shape)
y=np.array(y)
y=np.expand_dims(y,axis=-1)
print(y)
print(y.shape)

[[ 1. 23.  3.  8.]
 [ 1. 15.  2.  7.]
 [ 1. 24.  4.  9.]
 [ 1. 29.  5.  4.]
 [ 1. 31.  7.  6.]]
(5, 4)
[[6562]
 [4569]
 [6897]
 [7562]
 [8234]]
(5, 1)


Transpose The X Matrix 

In [124]:
x_transpose=x.T
print(x_transpose)
print(x_transpose.shape)

[[ 1.  1.  1.  1.  1.]
 [23. 15. 24. 29. 31.]
 [ 3.  2.  4.  5.  7.]
 [ 8.  7.  9.  4.  6.]]
(4, 5)


## Multiply The Xtranspose by X take care xt*x not x*xt **bold text**

In [125]:
x_mult_x_transpose=np.matmul(x.T,x)
print(x_mult_x_transpose)
print(x_mult_x_transpose.shape)

[[   5.  122.   21.   34.]
 [ 122. 3132.  557.  807.]
 [  21.  557.  103.  136.]
 [  34.  807.  136.  246.]]
(4, 4)


Get The Matrix inverse

In [126]:
x_mult_x_transpose_all_inverse=np.linalg.inv(x_mult_x_transpose)
print(x_mult_x_transpose_all_inverse)
print(x_mult_x_transpose_all_inverse.shape)

[[ 1.66083333e+01 -6.52380952e-01  1.28452381e+00 -8.65476190e-01]
 [-6.52380952e-01  4.89795918e-02 -1.43537415e-01  8.84353741e-03]
 [ 1.28452381e+00 -1.43537415e-01  5.06292517e-01  1.34353741e-02]
 [-8.65476190e-01  8.84353741e-03  1.34353741e-02  8.72448980e-02]]
(4, 4)


Multiply The Inversed Matrix multiply by the X transpose matrix

In [127]:
x_mult_x_transpose_all_inverse_multiplyby_xtranspose=np.dot(x_mult_x_transpose_all_inverse,x_transpose)
print(x_mult_x_transpose_all_inverse_multiplyby_xtranspose)
print(x_mult_x_transpose_all_inverse_multiplyby_xtranspose.shape)

[[-1.46666667  3.33333333 -1.7         0.65        0.18333333]
 [ 0.11428571 -0.14285714  0.02857143  0.08571429 -0.08571429]
 [-0.39047619  0.23809524 -0.01428571 -0.29285714  0.45952381]
 [ 0.07619048 -0.0952381   0.18571429 -0.19285714  0.02619048]]
(4, 5)


Get The Thetass

In [128]:
thetas=np.dot(x_mult_x_transpose_all_inverse_multiplyby_xtranspose,y)
print(thetas)
print(thetas.shape)

[[305.7       ]
 [236.68571429]
 [ -3.84285714]
 [102.95714286]]
(4, 1)


test the model

In [134]:
x_test=np.array([ 1,25,  3,  10])
y_test=7485
result=np.dot(thetas.T,x_test)
print("Accuracy Result:",100-((y_test-result)/y_test)*100)

Accuracy Result: [96.7386201]
